# Site settings
title: My Journey Into Quant Finance
description: 
url: "https://github.com/fabioandco/my-journey-into-quant-finance/edit/gh-pages/_config.yml"
author:
  name: "Fabio"
  email: ""
  url: ""

# Build settings
baseurl: /my-journey-into-quant-finance/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
